name: json_native
description: Extension and utils to use Map/List decoded from json easier.
homepage: https://github.com/timnew/json_native
version: 0.1.0

environment:
  sdk: '>=2.19.0'
# dependencies:

dev_dependencies:
  test: ^1.24.6
