name: json_native
description: Extension and utils to use Map/List decoded from json easier.
homepage: https://github.com/timnew/json_native
version: 0.2.0

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:

dev_dependencies:
  lint: ^2.1.2
  test: ^1.24.6
